package pojo;
// Generated Oct 1, 2021 11:35:14 AM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import DAO.DAOProduct;
import java.util.List;
import javax.faces.bean.ManagedBean;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Product generated by hbm2java
 */
@ManagedBean
public class Product implements java.io.Serializable {

    private Integer id;
    private String RoomType;
    private String AgeCategory;
    private String Available;
    private List<Product> productList;

    public List<Product> getProductList() {
        return productList == null ? this.getAllRecords() : productList;
    }

    public void setProductList(List<Product> productList) {
        this.productList = productList;
    }

    public List<Product> getAllRecords() {
        DAOProduct product = new DAOProduct();
        return product.retrveTblproduct();
    }

    public String getById() {
        String idProduct = id.toString();
        DAOProduct product = new DAOProduct();
        List<Product> listProduct = product.getbyID(idProduct);
        try {
            if (listProduct != null) {
                RoomType = listProduct.get(0).RoomType;
                AgeCategory = listProduct.get(0).AgeCategory;
                Available = listProduct.get(0).Available;

                return "dashboard";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "dashboard_error_search";
    }

    public String saveProduct() {
        DAOProduct product = new DAOProduct();
        product.addProduct(this);
        RoomType = "";
        AgeCategory = "";
        Available = "";

        return "dashboard";
    }

    public String editProduct() {
        DAOProduct product = new DAOProduct();
        product.editUser(this);
        RoomType = "";
        AgeCategory = "";
        Available = "";
        return "dashboard";
    }

    public String deleteProduct() {
        DAOProduct product = new DAOProduct();
        product.deleteUser(id);
        RoomType = "";
        AgeCategory = "";
        Available = "";
        return "dashboard";
    }

    public Product() {
    }

    public Product(String RoomType, String AgeCategory, String Available) {
        this.RoomType = RoomType;
        this.AgeCategory = AgeCategory;
        this.Available = Available;

    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRoomType() {
        return this.RoomType;
    }

    public void setRoomType(String RoomType) {
        this.RoomType = RoomType;
    }

    public String getAgeCategory() {
        return this.AgeCategory;
    }

    public void setAgeCategory(String AgeCategory) {
        this.AgeCategory = AgeCategory;
    }

    public String getAvailable() {
        return this.Available;
    }

    public void setAvailable(String Available) {
        this.Available = Available;
    }

}
